/** Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "Statechart.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_d_Dispensed_Product(Statechart* handle);
static void enact_d_Return_Credit(Statechart* handle);
static void enseq_d_Idle_default(Statechart* handle);
static void enseq_d_Coin_Insertion_default(Statechart* handle);
static void enseq_d_Product_Browser_default(Statechart* handle);
static void enseq_d_Dispensed_Product_default(Statechart* handle);
static void enseq_d_Return_Credit_default(Statechart* handle);
static void enseq_d_default(Statechart* handle);
static void exseq_d_Idle(Statechart* handle);
static void exseq_d_Coin_Insertion(Statechart* handle);
static void exseq_d_Product_Browser(Statechart* handle);
static void exseq_d_Dispensed_Product(Statechart* handle);
static void exseq_d_Return_Credit(Statechart* handle);
static void exseq_d(Statechart* handle);
static void react_d__entry_Default(Statechart* handle);

/*! State machine reactions. */
static sc_integer react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Idle. */
static sc_integer d_Idle_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Coin Insertion. */
static sc_integer d_Coin_Insertion_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Product Browser. */
static sc_integer d_Product_Browser_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Dispensed Product. */
static sc_integer d_Dispensed_Product_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Return Credit. */
static sc_integer d_Return_Credit_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);




static void statechart_internal_set_saldo(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_custo(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_option(Statechart* handle, sc_integer value)
;


static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_internal_set_saldo(handle, 0);
	statechart_internal_set_custo(handle, 0);
	statechart_internal_set_option(handle, 0);
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_d_default(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_d(handle);
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_d_Idle :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_D_IDLE] == Statechart_d_Idle
			);
				break;
		case Statechart_d_Coin_Insertion :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_D_COIN_INSERTION] == Statechart_d_Coin_Insertion
			);
				break;
		case Statechart_d_Product_Browser :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_D_PRODUCT_BROWSER] == Statechart_d_Product_Browser
			);
				break;
		case Statechart_d_Dispensed_Product :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_D_DISPENSED_PRODUCT] == Statechart_d_Dispensed_Product
			);
				break;
		case Statechart_d_Return_Credit :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_D_RETURN_CREDIT] == Statechart_d_Return_Credit
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->ifaceBut.E1_raised = bool_false;
	handle->ifaceBut.E2_raised = bool_false;
	handle->ifaceBut.browse_raised = bool_false;
	handle->ifaceBut.enter_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_d_Idle :
		{
			d_Idle_react(handle,-1);
			break;
		}
		case Statechart_d_Coin_Insertion :
		{
			d_Coin_Insertion_react(handle,-1);
			break;
		}
		case Statechart_d_Product_Browser :
		{
			d_Product_Browser_react(handle,-1);
			break;
		}
		case Statechart_d_Dispensed_Product :
		{
			d_Dispensed_Product_react(handle,-1);
			break;
		}
		case Statechart_d_Return_Credit :
		{
			d_Return_Credit_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		handle->doCompletion = bool_false;
		do
		{ 
			if (handle->completed == bool_true)
			{ 
				handle->doCompletion = bool_true;
			} 
			handle->completed = bool_false;
			micro_step(handle);
			handle->doCompletion = bool_false;
		} while (handle->completed == bool_true);
		clear_in_events(handle);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_but_raise_e1(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_but_E1);
	run_cycle(handle);
}

void statechart_but_raise_e2(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_but_E2);
	run_cycle(handle);
}

void statechart_but_raise_browse(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_but_browse);
	run_cycle(handle);
}

void statechart_but_raise_enter(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_but_enter);
	run_cycle(handle);
}




static void statechart_internal_set_saldo(Statechart* handle, sc_integer value)
{
	handle->internal.Saldo = value;
}
static void statechart_internal_set_custo(Statechart* handle, sc_integer value)
{
	handle->internal.Custo = value;
}
static void statechart_internal_set_option(Statechart* handle, sc_integer value)
{
	handle->internal.option = value;
}


/* implementations of all internal functions */

static void enact_d_Dispensed_Product(Statechart* handle)
{
	handle->completed = bool_true;
}

static void enact_d_Return_Credit(Statechart* handle)
{
	handle->completed = bool_true;
}

/* 'default' enter sequence for state Idle */
static void enseq_d_Idle_default(Statechart* handle)
{
	/* 'default' enter sequence for state Idle */
	handle->stateConfVector[0] = Statechart_d_Idle;
}

/* 'default' enter sequence for state Coin Insertion */
static void enseq_d_Coin_Insertion_default(Statechart* handle)
{
	/* 'default' enter sequence for state Coin Insertion */
	handle->stateConfVector[0] = Statechart_d_Coin_Insertion;
}

/* 'default' enter sequence for state Product Browser */
static void enseq_d_Product_Browser_default(Statechart* handle)
{
	/* 'default' enter sequence for state Product Browser */
	handle->stateConfVector[0] = Statechart_d_Product_Browser;
}

/* 'default' enter sequence for state Dispensed Product */
static void enseq_d_Dispensed_Product_default(Statechart* handle)
{
	/* 'default' enter sequence for state Dispensed Product */
	enact_d_Dispensed_Product(handle);
	handle->stateConfVector[0] = Statechart_d_Dispensed_Product;
}

/* 'default' enter sequence for state Return Credit */
static void enseq_d_Return_Credit_default(Statechart* handle)
{
	/* 'default' enter sequence for state Return Credit */
	enact_d_Return_Credit(handle);
	handle->stateConfVector[0] = Statechart_d_Return_Credit;
}

/* 'default' enter sequence for region d */
static void enseq_d_default(Statechart* handle)
{
	/* 'default' enter sequence for region d */
	react_d__entry_Default(handle);
}

/* Default exit sequence for state Idle */
static void exseq_d_Idle(Statechart* handle)
{
	/* Default exit sequence for state Idle */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Coin Insertion */
static void exseq_d_Coin_Insertion(Statechart* handle)
{
	/* Default exit sequence for state Coin Insertion */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Product Browser */
static void exseq_d_Product_Browser(Statechart* handle)
{
	/* Default exit sequence for state Product Browser */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Dispensed Product */
static void exseq_d_Dispensed_Product(Statechart* handle)
{
	/* Default exit sequence for state Dispensed Product */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state Return Credit */
static void exseq_d_Return_Credit(Statechart* handle)
{
	/* Default exit sequence for state Return Credit */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for region d */
static void exseq_d(Statechart* handle)
{
	/* Default exit sequence for region d */
	/* Handle exit of all possible states (of Statechart.d) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_d_Idle :
		{
			exseq_d_Idle(handle);
			break;
		}
		case Statechart_d_Coin_Insertion :
		{
			exseq_d_Coin_Insertion(handle);
			break;
		}
		case Statechart_d_Product_Browser :
		{
			exseq_d_Product_Browser(handle);
			break;
		}
		case Statechart_d_Dispensed_Product :
		{
			exseq_d_Dispensed_Product(handle);
			break;
		}
		case Statechart_d_Return_Credit :
		{
			exseq_d_Return_Credit(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_d__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_d_Idle_default(handle);
}


static sc_integer react(Statechart* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer d_Idle_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Idle. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->ifaceBut.browse_raised == bool_true)
			{ 
				exseq_d_Idle(handle);
				statechart_internal_set_option(handle, 0);
				enseq_d_Product_Browser_default(handle);
				react(handle,0);
				transitioned_after = 0;
			}  else
			{
				if (handle->ifaceBut.E1_raised == bool_true)
				{ 
					exseq_d_Idle(handle);
					statechart_internal_set_saldo(handle, (handle->internal.Saldo + 1));
					enseq_d_Coin_Insertion_default(handle);
					react(handle,0);
					transitioned_after = 0;
				}  else
				{
					if (handle->ifaceBut.E2_raised == bool_true)
					{ 
						exseq_d_Idle(handle);
						statechart_internal_set_saldo(handle, (handle->internal.Saldo + 2));
						enseq_d_Coin_Insertion_default(handle);
						react(handle,0);
						transitioned_after = 0;
					} 
				}
			}
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer d_Coin_Insertion_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Coin Insertion. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->ifaceBut.E1_raised == bool_true)
			{ 
				exseq_d_Coin_Insertion(handle);
				statechart_internal_set_saldo(handle, (handle->internal.Saldo + 1));
				enseq_d_Coin_Insertion_default(handle);
				react(handle,0);
				transitioned_after = 0;
			}  else
			{
				if (handle->ifaceBut.browse_raised == bool_true)
				{ 
					exseq_d_Coin_Insertion(handle);
					statechart_internal_set_option(handle, 0);
					enseq_d_Product_Browser_default(handle);
					react(handle,0);
					transitioned_after = 0;
				}  else
				{
					if (handle->ifaceBut.E2_raised == bool_true)
					{ 
						exseq_d_Coin_Insertion(handle);
						statechart_internal_set_saldo(handle, (handle->internal.Saldo + 2));
						enseq_d_Coin_Insertion_default(handle);
						react(handle,0);
						transitioned_after = 0;
					} 
				}
			}
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer d_Product_Browser_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Product Browser. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->ifaceBut.E1_raised == bool_true)
			{ 
				exseq_d_Product_Browser(handle);
				statechart_internal_set_saldo(handle, (handle->internal.Saldo + 1));
				enseq_d_Coin_Insertion_default(handle);
				react(handle,0);
				transitioned_after = 0;
			}  else
			{
				if (((handle->ifaceBut.enter_raised) == bool_true) && ((((handle->internal.Saldo) >= (handle->internal.Custo)) && ((handle->internal.option) != (0))) == bool_true))
				{ 
					exseq_d_Product_Browser(handle);
					statechart_internal_set_saldo(handle, (handle->internal.Saldo - handle->internal.option));
					enseq_d_Dispensed_Product_default(handle);
					react(handle,0);
					transitioned_after = 0;
				}  else
				{
					if (((handle->ifaceBut.enter_raised) == bool_true) && (((handle->internal.option) == (0)) == bool_true))
					{ 
						exseq_d_Product_Browser(handle);
						enseq_d_Return_Credit_default(handle);
						react(handle,0);
						transitioned_after = 0;
					}  else
					{
						if (((handle->ifaceBut.enter_raised) == bool_true) && (((handle->internal.Saldo) < (handle->internal.Custo)) == bool_true))
						{ 
							exseq_d_Product_Browser(handle);
							enseq_d_Product_Browser_default(handle);
							react(handle,0);
							transitioned_after = 0;
						}  else
						{
							if (((handle->ifaceBut.browse_raised) == bool_true) && (((handle->internal.option) < (3)) == bool_true))
							{ 
								exseq_d_Product_Browser(handle);
								handle->internal.option++;
								enseq_d_Product_Browser_default(handle);
								react(handle,0);
								transitioned_after = 0;
							}  else
							{
								if (handle->ifaceBut.E2_raised == bool_true)
								{ 
									exseq_d_Product_Browser(handle);
									statechart_internal_set_saldo(handle, (handle->internal.Saldo + 2));
									enseq_d_Coin_Insertion_default(handle);
									react(handle,0);
									transitioned_after = 0;
								}  else
								{
									if (((handle->ifaceBut.browse_raised) == bool_true) && (((handle->internal.option) == (3)) == bool_true))
									{ 
										exseq_d_Product_Browser(handle);
										statechart_internal_set_option(handle, 0);
										enseq_d_Product_Browser_default(handle);
										react(handle,0);
										transitioned_after = 0;
									} 
								}
							}
						}
					}
				}
			}
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer d_Dispensed_Product_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Dispensed Product. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Dispensed Product */
		handle->stateConfVector[0] = Statechart_last_state;
		/* 'default' enter sequence for state Idle */
		handle->stateConfVector[0] = Statechart_d_Idle;
		react(handle,0);
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	}
	return transitioned_after;
}

static sc_integer d_Return_Credit_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Return Credit. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Return Credit */
		handle->stateConfVector[0] = Statechart_last_state;
		statechart_internal_set_saldo(handle, handle->internal.Saldo - handle->internal.Saldo);
		/* 'default' enter sequence for state Idle */
		handle->stateConfVector[0] = Statechart_d_Idle;
		react(handle,0);
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	}
	return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_but_E1:
		{
			handle->ifaceBut.E1_raised = bool_true;
			return bool_true;
		}
		case Statechart_but_E2:
		{
			handle->ifaceBut.E2_raised = bool_true;
			return bool_true;
		}
		case Statechart_but_browse:
		{
			handle->ifaceBut.browse_raised = bool_true;
			return bool_true;
		}
		case Statechart_but_enter:
		{
			handle->ifaceBut.enter_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
